# Generated by Django 5.2.1 on 2025-08-08 18:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="student",
        ),
    ]
